VERSION=0.2.0
PROJROOT=$(HOME)/cpm
GOPATH=$(HOME)/cpm

build:
	        go install crunchy.com/cpmagent
	        go install crunchy.com/cpmagent/cpmagentserver
	        go install crunchy.com/cpmagent/cpmagentclient

