VERSION=0.2.0
PROJROOT=$(HOME)/cpm
GOPATH=$(HOME)/cpm

build:
	        go install crunchy.com/dummy
	        go install crunchy.com/dummy/dummyserver
	        go install crunchy.com/dummy/dummyclient

