VERSION=0.2.0
PROJROOT=$(HOME)/cpm
GOPATH=$(HOME)/cpm

build:
	        go install crunchy.com/backup
	        go install crunchy.com/backup/backupjob
	        go install crunchy.com/backup/backupserver

