#!/bin/bash

# Copyright 2015 Crunchy Data Solutions, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# configure a node to be a pgpool node
# $1 is the list of server names colon delimited e.g. server1:server2
#

source /opt/cpm/bin/setenv.sh
export DOMAIN=crunchy.lab
# format the user ip list
IFS=":"
iparr=($1)
entire=""
arrayLength=${#iparr[@]}
lastIndex=$((arrayLength - 1))
counter=0
for i in ${iparr[@]}; do
	echo $lastIndex $counter
        if [ $lastIndex -eq $counter ];  then
        	entire="${entire}${i}.${DOMAIN}"
	else
                entire="${entire}${i}.${DOMAIN},"
        fi
	(( counter += 1 ))
done
PG_HOST_LIST=$entire

echo $PG_HOST_LIST

echo $PG_HOST_LIST "is the user ip list" >> $CLUSTER_LOG

echo configure pgpool >> $CLUSTER_LOG
systemctl stop pgpool.service

echo configure pgpool config files >> $CLUSTER_LOG

pgtemplates -i /opt/cpm/conf/pgpool/pgpool.conf.template  \
	-t pgpool.conf \
	-m pgpool \
	-o /etc/pgpool-II-93/pgpool.conf \
	-useriplist "${PG_HOST_LIST}" &>> $CLUSTER_LOG

systemctl start pgpool.service

