#!/bin/bash

# Copyright 2015 Crunchy Data Solutions, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# ping the postgres server and report a simple status
# $1 - host
# $2 - port
# $3 - user
# $4 - password
# $5 - database
#

export PGPASSWORD=$4

psql -h $1 -p $2 -e -a -c 'select now()' -U $3 $5 > /dev/null 2> /dev/null 
if [ $? -ne 0 ]; then
	echo -n "down"
	exit
fi
echo -n "up"

