#!/bin/bash -x

# Copyright 2015 Crunchy Data Solutions, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# move an existing data volume to a backup location
# and replace it with a restored data volume
# $1 is the container name
#
DATA_DIR=$1
CONTAINER=$2

EVENT_LOG=/tmp/server-events.log
echo volume to switch is $CONTAINER in $DATA_DIR >> $EVENT_LOG

echo `date` >> $EVENT_LOG
mv $DATA_DIR/$CONTAINER $DATA_DIR/$CONTAINER-orig
mv $DATA_DIR/$CONTAINER-restore $DATA_DIR/$CONTAINER

exit 0
