#!/bin/bash -x

# Copyright 2015 Crunchy Data Solutions, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# delete a disk volume for a pg container
# $1 is the full path to the server's PGDataPath/ContainerName
#
FULLPATH=$1

EVENT_LOG=/tmp/server-events.log
echo "volume to delete is ["$FULLPATH"]" >> $EVENT_LOG

echo `date` >> $EVENT_LOG
rm -rf $FULLPATH

exit 0
