VERSION=0.2.0
PROJROOT=$HOME/cpm
GOPATH=$HOME/cpm

build:
		cd cpm-dashboard && make
		cd cpm-base && make  
		cd cpm-admin && make  
		cd cpm && make 
		cd cpm-node && make  
		cd cpm-pgpool && make
		cd cpm-backup && make
		cd cpm-backup-job && make
		cd cpm-mon && make




