VERSION=0.2.0
PROJROOT=$HOME/cpm
GOPATH=$HOME/cpm

build:
		cd crunchy-dashboard && make
		cd crunchy-base && make  
		cd crunchy-admin && make  
		cd crunchy-cpm && make 
		cd crunchy-node && make  
		cd crunchy-pgpool && make
		cd crunchy-backup && make
		cd crunchy-backup-job && make
		cd crunchy-mon && make




