export GOPATH=$(HOME)/crunchy-postgresql-manager

build:
		go install crunchy.com/util
		go install crunchy.com/mylog
		go install crunchy.com/admindb
		go install crunchy.com/kubeclient
		go install crunchy.com/sec
		go install crunchy.com/adminapi
		go install crunchy.com/cpmagent
		go install crunchy.com/cpmagent/cpmagentserver
		go install crunchy.com/cpmagent/cpmagentclient
		go install crunchy.com/dummy
		go install crunchy.com/dummy/dummyserver
		go install crunchy.com/dummy/dummyclient
		go install crunchy.com/template
		go install crunchy.com/backup
		go install crunchy.com/backup/backupjob
		go install crunchy.com/backup/backupserver
		go install crunchy.com/mon
		go install crunchy.com/mon/monserver
		go install crunchy.com/dockerapi



